In [1]:
import numpy as np
import pandas as pd
import seaborn as sb

In [2]:
df = pd.read_csv("simp.csv")

In [3]:
df.head()

A  B  C  RESULT
0  0  1  0       1
1  1  0  0       0
2  0  0  0       1
3  0  0  1       1
4  0  0  0       0

In [4]:
import sklearn.linear_model as sklin


In [5]:
model = sklin.LogisticRegression()

In [6]:
from sklearn.model_selection import train_test_split

In [7]:
X_train, X_test, y_train, y_test = train_test_split(df.drop('RESULT',axis=1), df['RESULT'], test_size=0.33, random_state=42)

In [8]:
model.fit(X_train,y_train)

/Applications/anaconda_dist/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='warn',
          n_jobs=None, penalty='l2', random_state=None, solver='warn',
          tol=0.0001, verbose=0, warm_start=False)

In [9]:
pred = model.predict(X_test)

In [10]:
np.mean(pred != y_test)

0.020202020202020204

In [11]:
import sklearn.metrics as skmet

In [12]:
skmet.confusion_matrix(y_test,pred)

array([[43,  0],
       [ 2, 54]])

In [13]:
print(skmet.classification_report(y_test,pred))

              precision    recall  f1-score   support

           0       0.96      1.00      0.98        43
           1       1.00      0.96      0.98        56

   micro avg       0.98      0.98      0.98        99
   macro avg       0.98      0.98      0.98        99
weighted avg       0.98      0.98      0.98        99



In [14]:
model.coef_

array([[0.26709818, 3.39645407, 4.55738413]])

In [15]:
model.intercept_

array([-1.80992342])

In [16]:
import math
def predict(a,b,c):
    return 1 / (1 + math.exp(-1*(0.26*a + 3.39*b + 4.55*c -1.8)))

In [17]:
pred

array([0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1,
       1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0,
       1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1,
       0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0])

In [18]:
X_test.head(5)

A  B  C
203  0  0  0
266  0  0  1
152  0  0  0
9    0  1  1
233  0  0  0

In [19]:
print(predict(0,0,0))
print(predict(0,0,1))
print(predict(0,1,1))

0.14185106490048777
0.9399133498259924
0.9978497100922109
